services:
  mongodb:
    image: mongo:latest
    container_name: food_ordering_mongodb
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    container_name: food_ordering_redis
    ports:
      - "6379:6379"

  user-service:
    build:
      context: ./backend
    container_name: food_ordering_user_service
    environment:
      - SERVICE_NAME=user-service
      - MONGODB_URI=mongodb://mongodb:27017/food_ordering
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis

  menu-service:
    build:
      context: ./backend
    container_name: food_ordering_menu_service
    environment:
      - SERVICE_NAME=menu-service
      - MONGODB_URI=mongodb://mongodb:27017/food_ordering
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis

  order-service:
    build:
      context: ./backend
    container_name: food_ordering_order_service
    environment:
      - SERVICE_NAME=order-service
      - MONGODB_URI=mongodb://mongodb:27017/food_ordering
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis

  nginx:
    image: nginx:alpine
    container_name: food_ordering_nginx
    ports:
      - "3001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - user-service
      - menu-service
      - order-service
